#!/usr/bin/env bash
# new-plan.sh — scaffold a complete, viewer-valid plan silo from canonical/templates.
#
# The instantiation half of the protocol base (PROTOCOL.md §9): tier-1.2 working files
# rendered from templates, tier-1.1 governance docs pulled in by sync-canonical.sh, plus
# the argv-less <id>-tick.sh shim the viewer/launchd need to drive the generic engine.
#
# Usage: workspace-bin/new-plan.sh <kebab-case-id> ["one-line goal"]

set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TPL="$REPO/memory-plan/canonical/templates"

ID="${1:-}"
GOAL="${2:-<one-line goal — fill me in>}"
[[ "$ID" =~ ^[a-z0-9][a-z0-9-]*$ ]] || { echo "usage: new-plan.sh <kebab-case-id> [\"one-line goal\"]" >&2; exit 1; }
[[ -d "$TPL" ]] || { echo "no templates dir: $TPL" >&2; exit 1; }

PLAN="$REPO/memory-plan/plans/$ID"
[[ -e "$PLAN" ]] && { echo "refusing: $PLAN already exists" >&2; exit 1; }

DATE="$(date '+%Y-%m-%d')"
mkdir -p "$PLAN/audits" "$PLAN/tick-logs"

for t in "$TPL"/*.template.*; do
  name="$(basename "$t")"
  dest="${name/.template/}"
  sed -e "s|{{PLAN_ID}}|$ID|g" \
      -e "s|{{GOAL}}|$GOAL|g" \
      -e "s|{{DATE}}|$DATE|g" \
      -e "s|{{REPO}}|$REPO|g" \
      -e "s|{{HOME}}|$HOME|g" \
      "$t" > "$PLAN/$dest"
  echo "scaffolded plans/$ID/$dest"
done

printf 'v0.0\n' > "$PLAN/VERSION"
echo "scaffolded plans/$ID/VERSION (v0.0)"

SHIM="$REPO/workspace-bin/$ID-tick.sh"
if [[ -e "$SHIM" ]]; then
  echo "shim already exists, leaving untouched: workspace-bin/$ID-tick.sh"
else
  # The viewer and launchd spawn tick_command with no argv (PROTOCOL.md §7) — this
  # shim is the binding between them and the generic engine.
  printf '#!/usr/bin/env bash\n# generated by new-plan.sh — argv-less front for plan-tick.sh (PROTOCOL.md §7)\nexec "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/plan-tick.sh" %s "$@"\n' "$ID" > "$SHIM"
  chmod +x "$SHIM"
  echo "scaffolded workspace-bin/$ID-tick.sh (shim → plan-tick.sh $ID)"
fi

"$REPO/workspace-bin/sync-canonical.sh" >/dev/null
echo "canonical docs synced into plans/$ID/"

echo
"$REPO/workspace-bin/plan-lint.sh" "$ID" || true

cat <<EOF

plan '$ID' is viewer-valid now — the viewer (:7892) lists it within 60s.
Before its first step runs (PROTOCOL.md §9):
  1. ROADMAP.md             write the blocks: intent, exit criterion, order
  2. INVENTORY.md           decompose to atomic steps + runtime-observable done-evidence
  3. TICK_PROMPT.md         fill the bindings (search for '<FILL')
  4. COMPONENT_REGISTRY.md  probe current reality and record it
  5. DECISIONS.md           log D1: why this plan exists + the approach
The tick plist is NOT loaded — enable the chain per-plan via the viewer's Automation tab
(or launchctl) once the plan is filled in. Interactive work needs no plist.
EOF
